### ISSUE TITLE
Problem doing JSON post

### ISSUE THREAD

**Issue by lulu88** [alexrsagen/node-es6-request#4]
Hi,

I am trying to do a POST with JSON data to our backend server like this:

``` javascript
request.post(Config.get(appconfig.backend_endpoint))
  .headers({
    "Content-Type": "application/json"
  })
  .json(jsonData)
  .then(([body, res]) => {
    let jsResult = JSON.parse(body)
    console.log(jsResult)
    resolve(jsResult)
  })
```

However on my server I keep seeing 'Media type separator is missing. When I do this post from the Google Chrome Advanced Rest Client it works (the request headers look like this):

`POST /endpoint HTTP/1.1
 HOST: our_host_here
 content-type: application/json
 content-length: 380
`

Any idea how to get this working? I have tried doing a .send instead of the .json, but no luck.

**Comment by alexrsagen** [comment]
Hi, using `.json()` will send your JSON object URL encoded. Perhaps i should document this better...

Here's some code that should work for you:

``` javascript
const stringified = JSON.stringify(jsonData);
request.post(Config.get(appconfig.backend_endpoint))
  .headers({
    "Content-Type": "application/json"
    "Content-Length": Buffer.from(stringified).byteLength
  })
  .send(stringified)
  .then(([body, res]) => {
    let jsResult = JSON.parse(body);
    console.log(jsResult);
    resolve(jsResult);
  });
```

**Comment by lulu88** [comment]
Thank you very much for the quick response - I will give this a try :)

**Comment by alexrsagen** [comment]
I updated my comment to calculate correct length if you're using any unicode characters. If you don't use any unicode you should be fine with just `stringified.length`, but it's better to be on the safe side.

**Comment by lulu88** [comment]
Thank you so much it is working perfectly now :100: :+1:
